version: "3.7"
services:
  proyectos-backend-multi:
    container_name: proyectos-multi
    image: proyectos-multi:v1
    build:
      context: .
    ports:
      - "4002:4002"
    networks:
      - proyectos-app
networks:
  proyectos-app:
